### PR TITLE
Update README.md with link to examples

### PR DESCRIPTION
**Pull request by cantino**
@dsander, do you have other examples that aren't showing up? I think it may only be showing things depending on the most recent version of the gem.

### CODE REVIEW

**Comment by dsander** [comment]
Yes there are a few more: http://huginnio.herokuapp.com/agent_gems

I guess not many have been published as gems.

**Comment by cantino** [comment]
Should I add a link to your huginnio as well, or is it still too beta?

**Comment by dsander** [comment]
How about we link the available gems in the readme directly for now?

**Comment by cantino** [comment]
Is there a reason that you haven't published yours as gems?

**Comment by dsander** [comment]
As far as I remember the only reason was that the client did not have a rubygems account.

**Comment by cantino** [comment]
Ok, I added links to them.

**Comment by dsander** [comment]
Nice, thank you 👏

**Pull request merged**
